hospital-app/config/routes.rb
Rails.application.routes.draw do
  get 'patients/new' , to: 'patients#new'
  get "patients", to: "patients#index"
  get 'patients/:id' , to: 'patients#show' , as:'patient'
  post 'patients' , to: 'patients#create'
  get "patients/:id/edit", to: "patients#edit", as:"patient_edit"
  patch "patients/:id", to: "patients#update"
  delete "patients/:id", to: "patients#destroy" , as:"patient_delete"

  root 'patients#patients'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hospital-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hospital-app/app/models/doctor.rb
class Doctor < ApplicationRecord
end

hospital-app/app/models/patient.rb
class Patient < ApplicationRecord

    validates :first_name, presence: true
    validates :diagnosis, presence: true
end

hospital-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hospital-app/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

    def index

        @doctors = Doctor.all 

    end
    

    def show
        @doctor =  Doctor.find(params[:id])

      end

      def create
        @doctor = Doctor.new(doctor_paramse)
         @doctor.save
         
       end 
       
       def new
       @doctor = Doctor.new  
       end 


       def edit
        @doctor = Doctor.find(params[:id])
      end



      def update
        doctor = Doctor.find(params[:id])
        doctor.update(params.require(:doctor).permit(:name, :family_name, :specialty, :zip_code))
          
     
      end


      def destroy
        Doctor.find(params[:id]).destroy
      end


       private 
def doctor_paramse
   params.require(:patient).permit(:name, :family_name, :specialty, :zip_code)
end

end

hospital-app/app/controllers/patients_controller.rb
class PatientsController < ApplicationController

    def index

        @patients = Patient.all 

    end
    

    def show
        @patient =  Patient.find(params[:id])

      end

      def create
        @patient = Patient.new(patient_paramse)
        if @patient.save
          redirect_to @patient
         else 
           render  'new'
         end 
       end 
       
       def new
       @patient = Patient.new  
       end 


       def edit
        @patient = Patient.find(params[:id])
      end



      def update
        patient = Patient.find(params[:id])
        patient.update(params.require(:patient).permit(:first_name, :last_name, :diagnosis, :born_on))
          
        redirect_to patient
      end


      def destroy
        Patient.find(params[:id]).destroy
      end


       private 
def patient_paramse
   params.require(:patient).permit(:first_name ,:last_name , :diagnosis , :born_on)
end

end

hospital-app/app/helpers/application_helper.rb
module ApplicationHelper
end

hospital-app/app/helpers/patients_helper.rb
module PatientsHelper
end

hospital-app/app/views/doctors/new.html.erb
ADD: <%= render doctor: 'form', locals: { doctor: @doctor } %>

hospital-app/app/views/doctors/show.html.erb
<h1> show work </h1>


 name :<%=  @doctor.name  %>
 <br>
 family name :<%=  @doctor.family_name %>
  <br>

  

hospital-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospitalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hospital-app/app/views/patients/_form.html.erb
<%= form_with model: @patient , local: true do |form| %>
<p>
first name :
<%= form.text_field :first_name%>
</p>
<p>
last name :
<%= form.text_field :last_name%>
</p>
<p>
diagnosis :
<%= form.text_field :diagnosis%>
</p>
<p>
born_on :
<%= form.text_field :born_on%>
</p>

<%= form.submit%>
<% end %>

hospital-app/app/views/patients/edit.html.erb
<h2> edit patient </h2>

edit: <%= render partial: 'form', locals: { patient: @patient } %>

hospital-app/app/views/patients/index.html.erb
<h2> All patients </h2>

<%@patients.each do |patient|%>
<div>

 firstname :<%=  link_to  patient.first_name  , patient %>
 
<div>
<% end %>

hospital-app/app/views/patients/new.html.erb
<h2> New patient </h2>

<% if @patient.errors.any? %>
<h3>  we have got problems ! </h3>

<ul>
 <% @patient.errors.full_messages.each do |msg| %>
 <li>
<%= msg %>
</li>
<%end %>
</ul>
<% end %>

ADD: <%= render partial: 'form', locals: { patient: @patient } %>

hospital-app/app/views/patients/show.html.erb
<h1> show work </h1>


 firstname :<%=  @patient.first_name  %>
 <br>
 lastname :<%=  @patient.last_name  %>
  <br>
 diagnosis : <%= @patient.diagnosis%>
  <br>
 DOB : <%= @patient.born_on%>
  <br>
 <%=  link_to  "edit"  , patient_edit_url %>
  <br>
 <%=  link_to  "Delete"  , patient_delete_url %>
  